REPORT_PROMPT = """Using all the data gathered from your tools, write a professional equity research report in Markdown format.

Follow this exact structure:

---

# {TICKER} — Equity Research Report
**{COMPANY NAME}** | {SECTOR} | {DATE}

---

## Executive Summary
2-3 sentence overview of the company and your key takeaway from the data. State whether the data signals are broadly positive, negative, or mixed.

---

## Price & Technicals
- Current price and recent price action (reference the 5-day OHLCV data)
- Position relative to 50-day and 200-day moving averages (bullish/bearish signal)
- 52-week range context — where is the stock trading relative to its range?
- Volume trends if notable
- Analyst consensus price target vs current price (upside/downside %)

---

## Financial Health
- Revenue trend (growing/declining, by how much YoY)
- Profitability: gross margin, operating income, net income trend
- EPS trend
- Balance sheet highlights: cash position, debt load, net debt
- One sentence on overall financial health

---

## Valuation
- P/E ratio (TTM and forward) — cheap, fair, or expensive vs typical market multiples?
- Any other valuation signals from the data
- Brief comment on whether current price appears justified by fundamentals

---

## News & Sentiment
- Summarize the 3-5 most significant recent headlines
- Identify the dominant sentiment tone (positive / negative / neutral / mixed)
- Flag any material events: earnings, product launches, regulatory news, lawsuits, leadership changes

---

## SEC Filings
- Most recent 10-K and 10-Q filing dates
- Note if filings appear current or if there are any gaps
- EDGAR links for reference

---

## Key Risks
List 3-5 specific risks grounded in the data:
- Risk 1
- Risk 2
- Risk 3

---

## Bull vs Bear Case

**Bull Case:**
2-3 specific reasons the stock could outperform, grounded in the data.

**Bear Case:**
2-3 specific reasons the stock could underperform, grounded in the data.

---

## Analyst Verdict
One clear paragraph summarizing your overall read on the stock. Reference the data. Do not sit on the fence — take a position based on what the data shows.

---

*Disclaimer: This report is generated by an AI and is for informational and educational purposes only. It does not constitute financial advice. Always conduct your own due diligence and consult a licensed financial advisor before making investment decisions.*

---

Write the full report now using the data you have gathered. Do not add sections beyond what is defined above. Do not invent or estimate any figures — use only what the tools returned."""
